### ISSUE TITLE
solution: Error when pull and push / divergent branches

### ISSUE THREAD

**Issue by camila-rahal** [UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica#2]
Hello, me and Jessica are facing an mutual error when push or pull github. 

Whenever I'm able to push and pull normally, she have this error, and vice versa. 

">>> /usr/bin/git push origin HEAD:refs/heads/main
To https://github.com/UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica
 ! [rejected]        HEAD -> main (fetch first)
error: failed to push some refs to 'https://github.com/UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.""

So, when I try to pull, as recommended, the following error occurs:

"From https://github.com/UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica
   88a5bc3..0ea037f  main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches."

To solve this, I enter my terminal: 

(base) camilabatistarahal@MacBook-Air-de-Camila ~ %  cd /applications/Working_Directory/Jessica_Camila_Project/Groupwork_Camila_Jessica
(base) camilabatistarahal@MacBook-Air-de-Camila Groupwork_Camila_Jessica % git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
(base) camilabatistarahal@MacBook-Air-de-Camila Groupwork_Camila_Jessica % git pull
Already up to date.

**Comment by DeAngelisA** [comment]
Hi @camila-rahal, 

I hope you're doing well! I've looked into the GitHub issues you and Jessica are experiencing, and I'd like to offer some guidance to help you both move forward smoothly.

Firstly, it seems the push rejections are happening because the repository on GitHub has updates that your local version lacks. This is a common situation when multiple people are working on the same project. To avoid this, before you push your changes, it's a good idea to pull the latest updates from GitHub with:

```sh
git pull origin main
```
(you can write this in the Terminal next to the RStudio console)

If you encounter messages about divergent branches, Git is basically asking for instructions on how to merge these differences. A simple way to set your preferred method is by configuring Git to use merging as the default strategy:

```sh
git config pull.rebase false
```

Then, you can safely pull again.

Regarding the merge conflicts and the message about an unfinished merge, it looks like there's a merge that was started but not completed. This usually requires manually resolving the conflicts. Here's how you can address it:

1. Check for unmerged files with `git status`.
2. Open the conflicted files, look for conflict markers (like `<<<<<<<`, `=======`, `>>>>>>>`), and decide how to integrate the changes.
3. After resolving each conflict, add the file to the staging area with `git add <file-name>`.
4. Complete the merge by committing the changes with `git commit -m "Resolved merge conflicts."`

This process should help in clearing up the current issues. Moving forward, it might be beneficial to coordinate who is pushing and when, especially if you're both working on similar parts of the project. This can help in minimizing conflicts. Additionally, using separate branches for individual tasks and then merging them into the main branch can also streamline your workflow.

I hope this helps! If you have any more questions or need further assistance, feel free to ask.
A.

**Comment by jessicaugowe** [comment]
Thanks for informing him about the issue @camila-rahal and thanks for the help @DeAngelisA.
